[ML Zoomcamp 1.7 - Introduction to NumPy](https://www.youtube.com/watch?v=Qa0-jYtRdbY)

Extra: [NumPy CheatSheet](https://media.datacamp.com/legacy/image/upload/v1676302459/Marketing/Blog/Numpy_Cheat_Sheet.pdf)

In [2]:
import numpy as np

# Single dimension array

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [7]:
a[2] = 5
a

array([1, 2, 5, 4])

In [8]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimension array

In [12]:
# 5 rows and 2 columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
# first row, second column
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
# first row
n[0]

array([ 1, 20,  3])

In [ ]:
# second column
n[:, 1]

array([20,  5,  8])

In [26]:
# fix random seed for reproducibility
np.random.seed(2)
# generate random array of 5 rows and 2 columns
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
# fix random seed for reproducibility
np.random.seed(2)
# generate random array of 5 rows and 2 columns with normal distribution
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [29]:
# fix random seed for reproducibility
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [30]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [31]:
a * 100

array([  0, 100, 200, 300, 400])

In [33]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [34]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [35]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

## Comparison operations

In [37]:
a

array([0, 1, 2, 3, 4])

In [36]:
a >= 2

array([False, False,  True,  True,  True])

In [38]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [41]:
# return boolean array
a > b

array([False, False,  True,  True,  True])

In [42]:
# return all elements of a that are greater than b
a[a > b]

array([2, 3, 4])

# Summarizing operatons

In [43]:
a

array([0, 1, 2, 3, 4])

In [44]:
a.max()

np.int64(4)

In [46]:
# standard deviation
a.std()

np.float64(1.4142135623730951)

In [47]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [48]:
n.sum()

np.int64(63)

In [49]:
n.max()

np.int64(20)